import { Asul, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import { PropsWithChildren } from "react";
import { BackgroundBeams, Header } from "./_components";
import ReactQueryProvider from "./providers/ReactQueryProvider";

const metadata: Metadata = {
  title: "Viennalytics",
  description: "Generated by create next app",
};

const asul = Asul({
  weight: "400",
  variable: "--font-asul",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  weight: "700",
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

const RootLayout = ({ children }: Readonly<PropsWithChildren>) => (
  <html lang="en">
  <body className={`${asul.variable} ${jetbrainsMono.variable} antialiased`}>
      <BackgroundBeams />
      <ReactQueryProvider>
        <div className="flex flex-col min-h-screen gap-5 p-3">
          <Header />
          {children}
        </div>
      </ReactQueryProvider>
    </body>
  </html>
);

export { metadata };
export default RootLayout;